# Generated by Django 2.2.5 on 2020-01-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GospelApp', '0002_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_photho',
            field=models.ImageField(upload_to='images'),
        ),
    ]
