# Generated by Django 2.2.5 on 2020-02-10 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GospelApp', '0004_videos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videos',
            options={'verbose_name': 'video', 'verbose_name_plural': 'video'},
        ),
    ]
