# Generated by Django 2.2.5 on 2020-02-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GospelApp', '0005_auto_20200210_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='content_details',
            field=models.TextField(default='details'),
        ),
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(upload_to='images'),
        ),
    ]
