# Generated by Django 2.2.5 on 2020-02-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GospelApp', '0006_auto_20200219_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_detail',
            field=models.TextField(default='article details'),
        ),
    ]
