# Generated by Django 2.2.5 on 2020-02-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GospelApp', '0007_article_article_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_image', models.ImageField(upload_to='images')),
                ('slide_title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'slides',
                'verbose_name_plural': 'slides',
            },
        ),
    ]
